services:
    marca.course_bundle.twig.course_extension:
        class: Marca\CourseBundle\Twig\CourseExtension
        arguments: ['@service_container']
        tags: 
            - { name:twig.extension}