imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: '@MarcaCourseBundle/Resources/config/services.yml' }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
      resource: "%kernel.root_dir%/config/routing.yml"
      strict_requirements: %kernel.debug%
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    session: ~
    default_locale: %locale%  
    trust_proxy_headers: false
    trusted_proxies: ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    # java: /usr/bin/java
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    port:      %mailer_port%
    encryption: %mailer_encryption%
    username:  %mailer_user%
    password:  %mailer_password%
    sender_address: %mailer_sender_address%
    spool: { type: memory }
    
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Marca\UserBundle\Entity\User
    registration:
        form:
            type: marca_user_registration
            #handler: marca_user.form.handler.registration
        confirmation:
            enabled:    true
    from_email:
        address:        %from_email%
        sender_name:    Marca Dev 

# Doctrine extensions    
stof_doctrine_extensions:
    default_locale: en_US
    orm:
        default:
            timestampable: true
            sluggable: true  
            
knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: KnpPaginatorBundle:Pagination:sliding.html.twig     # sliding pagination controls template
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template 
        
vich_uploader:
    db_driver: orm # or mongodb
    twig: true
    gaufrette: false # set to true to enable gaufrette support
    storage: vich_uploader.storage.file_system
    mappings:
        property_file:
            uri_prefix: %kernel.root_dir%/../uploads/files # uri prefix to resource
            upload_destination: %kernel.root_dir%/../uploads/files # gaufrette storage fs id, required
            namer: namer.upload_file # specify a file namer service id for this entity, null default
            directory_namer: directory_namer.upload_file # specify a directory namer service id for this entity, null default
            delete_on_remove: true # determines whether to delete file upon removal of entity
            inject_on_load: true # determines whether to inject a File instance upon load  
            
knp_snappy:
    pdf:
        enabled:    true
        binary:     %kernel.root_dir%/../../marca/vendor/google/wkhtmltopdf-i386/wkhtmltopdf-i386
        options:    []          
  
