parameters:
    database_driver:   pdo_mysql
    database_host:     localhost
    database_port:     3306
    database_name:     marca
    database_user:     root
    database_password: ddt123

    mailer_transport:  smtp
    mailer_host:       localhost
    mailer_port:       25
    mailer_sender_address: return@yourmail.com
    mailer_user:       afamiglietti
    mailer_password:   password
    mailer_encryption: tls
    from_email:        return@yourmail.com

    locale:            en
    secret:            b6ac9707094a9e6826d80d14ac32464b
