parameters:
    database_driver:   pdo_pgsql
    database_host:     localhost
    database_port:     5432
    database_name:     marca_db
    database_user:     xxxxxx
    database_password: xxxxxx

    mailer_transport:  smtp
    mailer_host:       xxxx
    mailer_port:       xxxx
    mailer_sender_address: xxxxxx
    mailer_user:       xxxxxx
    mailer_password:   xxxx
    mailer_ecryption:  xxx
    from_email:        xxxx

    locale:            en
    secret:            5bf101ce3605f4eeebe56bc4873d2b2b2
