parameters:
    database_driver:   pdo_pgsql
    database_host:     localhost
    database_port:     5432
    database_name:     marca_db
    database_user:     rlbaltha
    database_password: hdt71217

    mailer_transport:  smtp
    mailer_host:       pod51004.outlook.com
    mailer_port:       587
    mailer_sender_address: rlbaltha@uga.edu
    mailer_user:       rlbaltha@uga.edu
    mailer_password:   faithinas33d!
    mailer_ecryption:  tls
    from_email:        rlbaltha@uga.edu

    locale:            en
    secret:            5bf101ce3605f4eeebe56bc4873d2b2b2
